baseURL = "http://nef.is/"
title = "Nefis"
theme = "etch"
languageCode = "tr-TR"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Nefis tarifler"
  highlight = true

[markup.goldmark.renderer]
  unsafe = true